### ISSUE TITLE
ParserRunner throws exception

### ISSUE THREAD

**Issue by halirutan** [Skory/translator#1]
I bluntly used your code of the [ParserRunner](https://github.com/Skory/translator/blob/master/ts-generator/src/com/siliconmint/ts/ParserRunner.java) class, because it was the only thing I found on the net the showed how to use `com.intellij.core.JavaCoreApplicationEnvironment`.

It compiles find but throws an exception at runtime. I'm using IDEA 14.1.4. Can you confirm that you can run this file? I attach the exception and please note [the reason](https://devnet.jetbrains.com/message/5549140#5549140) why I look into this. 

Thank you very much in advance

```
Exception in thread "main" java.lang.IllegalArgumentException: Missing extension point: com.intellij.codeInsight.containerProvider in area null at     com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:331)
 at     com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:340)
 at     com.intellij.core.CoreApplicationEnvironment.addExtension(CoreApplicationEnvironment.java:279)
 at com.intellij.core.JavaCoreApplicationEnvironment.<init>(JavaCoreApplicationEnvironment.java:76)
 at Main.createProject(Main.java:44)
 at Main.createPsiFactory(Main.java:33)
 at Main.main(Main.java:20)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
 at java.lang.reflect.Method.invoke(Method.java:597)
 at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by halirutan** [comment]
OK, I'm doing something wrong myself. I checked out the whole repository and now it works. I have to look at all your dependencies because I'm sure I forgot something.
